import type {
  Usuario,
  Aluno,
  Equipamento,
  PlanoTreino,
  AlertaAcademia,
  SolicitacaoManutencao,
  ResumoFinanceiro,
  PontoReceita,
  KpiGerencia,
} from '@/types';

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const MOCK_USERS: Usuario[] = [
  {
    id: 'user-1',
    name: 'Arthur Emmanuel',
    email: 'arthur@gympro.com',
    role: 'aluno',
    avatarUrl: undefined,
    cpf: '123.456.789-00',
    phone: '(11) 99999-0001',
    criadoEm: '2024-03-01T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Ana Clara',
    email: 'anaclara@gympro.com',
    role: 'aluno',
    avatarUrl: undefined,
    cpf: '987.654.321-00',
    phone: '(11) 99999-0002',
    criadoEm: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Enrico',
    email: 'enrico@gympro.com',
    role: 'professor',
    avatarUrl: undefined,
    phone: '(11) 99999-0003',
    criadoEm: '2023-06-01T10:00:00Z',
  },
  {
    id: 'user-4',
    name: 'Beatriz',
    email: 'beatriz@gympro.com',
    role: 'professor',
    avatarUrl: undefined,
    phone: '(11) 99999-0004',
    criadoEm: '2023-08-01T10:00:00Z',
  },
  {
    id: 'user-5',
    name: 'Luiz Felipe',
    email: 'luizfelipe@gympro.com',
    role: 'gerencia',
    avatarUrl: undefined,
    phone: '(11) 99999-0005',
    criadoEm: '2023-01-01T10:00:00Z',
  },
];

export const MOCK_CREDENTIALS: Record<string, { password: string; usuarioId: string }> = {
  'arthur@gympro.com': { password: '123456', usuarioId: 'user-1' },
  'anaclara@gympro.com': { password: '123456', usuarioId: 'user-2' },
  'enrico@gympro.com': { password: '123456', usuarioId: 'user-3' },
  'beatriz@gympro.com': { password: '123456', usuarioId: 'user-4' },
  'luizfelipe@gympro.com': { password: '123456', usuarioId: 'user-5' },
};


export const MOCK_STUDENTS: Aluno[] = [
  {
    id: 'student-1',
    usuarioId: 'user-1',
    name: 'Arthur Emmanuel',
    email: 'arthur@gympro.com',
    phone: '(11) 99999-0001',
    cpf: '123.456.789-00',
    statusPagamento: 'adimplente',
    mensalidade: 120.0,
    diaVencimento: 10,
    matriculadoEm: '2024-03-01T10:00:00Z',
    ultimoPagamentoEm: '2024-05-10T08:00:00Z',
    planoTreinoAtivoId: 'plan-1',
    professorId: 'user-3',
    contatoEmergencia: '(11) 99888-0001',
  },
  {
    id: 'student-2',
    usuarioId: 'user-2',
    name: 'Ana Clara',
    email: 'anaclara@gympro.com',
    phone: '(11) 99999-0002',
    cpf: '987.654.321-00',
    statusPagamento: 'inadimplente',
    mensalidade: 120.0,
    diaVencimento: 5,
    matriculadoEm: '2024-01-15T10:00:00Z',
    ultimoPagamentoEm: '2024-04-05T08:00:00Z',
    planoTreinoAtivoId: 'plan-2',
    professorId: 'user-3',
  },
  {
    id: 'student-3',
    usuarioId: 'user-6',
    name: 'Pedro',
    email: 'pedro@email.com',
    phone: '(11) 99999-0006',
    cpf: '111.222.333-44',
    statusPagamento: 'adimplente',
    mensalidade: 150.0,
    diaVencimento: 15,
    matriculadoEm: '2024-02-20T10:00:00Z',
    ultimoPagamentoEm: '2024-05-15T08:00:00Z',
    planoTreinoAtivoId: undefined,
    professorId: 'user-4',
  },
  {
    id: 'student-4',
    usuarioId: 'user-7',
    name: 'Juliana',
    email: 'juliana@email.com',
    phone: '(11) 99999-0007',
    cpf: '555.666.777-88',
    statusPagamento: 'pendente',
    mensalidade: 120.0,
    diaVencimento: 20,
    matriculadoEm: '2024-04-01T10:00:00Z',
    planoTreinoAtivoId: 'plan-3',
    professorId: 'user-3',
  },
  {
    id: 'student-5',
    usuarioId: 'user-8',
    name: 'Lucas',
    email: 'lucas@email.com',
    phone: '(11) 99999-0008',
    cpf: '999.888.777-66',
    statusPagamento: 'adimplente',
    mensalidade: 180.0,
    diaVencimento: 1,
    matriculadoEm: '2023-11-01T10:00:00Z',
    ultimoPagamentoEm: '2024-05-01T08:00:00Z',
    planoTreinoAtivoId: 'plan-1',
    professorId: 'user-4',
  },
  {
    id: 'student-6',
    usuarioId: 'user-9',
    name: 'Ana Luiza',
    email: 'analuiza@email.com',
    phone: '(11) 99999-0009',
    cpf: '123.321.123-45',
    statusPagamento: 'inadimplente',
    mensalidade: 120.0,
    diaVencimento: 25,
    matriculadoEm: '2024-01-01T10:00:00Z',
    ultimoPagamentoEm: '2024-03-25T08:00:00Z',
    planoTreinoAtivoId: undefined,
    professorId: 'user-3',
  },
];


export const MOCK_WORKOUT_PLANS: PlanoTreino[] = [
  {
    id: 'plan-1',
    name: 'Hipertrofia — Nível A',
    alunoId: 'student-1',
    professorId: 'user-3',
    dificuldade: 'intermediario',
    diasPorSemana: 5,
    criadoEm: '2024-03-05T10:00:00Z',
    atualizadoEm: '2024-05-01T10:00:00Z',
    ativo: true,
    exercicios: [
      {
        id: 'ex-1',
        name: 'Supino Reto com Barra',
        grupoMuscular: 'Peito',
        sets: 4,
        reps: '8-10',
        segundosDescanso: 90,
        pesoKg: 60,
        notes: 'Controlar a descida por 3 segundos',
        seriesConcluidas: 0,
      },
      {
        id: 'ex-2',
        name: 'Crucifixo com Halteres',
        grupoMuscular: 'Peito',
        sets: 3,
        reps: '12',
        segundosDescanso: 60,
        pesoKg: 14,
        seriesConcluidas: 0,
      },
      {
        id: 'ex-3',
        name: 'Puxada Frontal',
        grupoMuscular: 'Costas',
        sets: 4,
        reps: '10-12',
        segundosDescanso: 90,
        pesoKg: 55,
        seriesConcluidas: 0,
      },
      {
        id: 'ex-4',
        name: 'Remada Curvada',
        grupoMuscular: 'Costas',
        sets: 3,
        reps: '10',
        segundosDescanso: 90,
        pesoKg: 50,
        notes: 'Manter coluna neutra',
        seriesConcluidas: 0,
      },
      {
        id: 'ex-5',
        name: 'Desenvolvimento com Halteres',
        grupoMuscular: 'Ombros',
        sets: 4,
        reps: '10-12',
        segundosDescanso: 75,
        pesoKg: 18,
        seriesConcluidas: 0,
      },
      {
        id: 'ex-6',
        name: 'Agachamento Livre',
        grupoMuscular: 'Pernas',
        sets: 4,
        reps: '8-10',
        segundosDescanso: 120,
        pesoKg: 80,
        notes: 'Descer até 90 graus',
        seriesConcluidas: 0,
      },
    ],
  },
  {
    id: 'plan-2',
    name: 'Condicionamento — Iniciante',
    alunoId: 'student-2',
    professorId: 'user-3',
    dificuldade: 'iniciante',
    diasPorSemana: 3,
    criadoEm: '2024-01-20T10:00:00Z',
    atualizadoEm: '2024-04-10T10:00:00Z',
    ativo: true,
    exercicios: [
      {
        id: 'ex-7',
        name: 'Esteira — Caminhada Rápida',
        grupoMuscular: 'Cardio',
        sets: 1,
        reps: '20 min',
        segundosDescanso: 0,
        seriesConcluidas: 0,
      },
      {
        id: 'ex-8',
        name: 'Leg Press 45°',
        grupoMuscular: 'Pernas',
        sets: 3,
        reps: '15',
        segundosDescanso: 60,
        pesoKg: 40,
        seriesConcluidas: 0,
      },
      {
        id: 'ex-9',
        name: 'Cadeira Extensora',
        grupoMuscular: 'Pernas',
        sets: 3,
        reps: '15',
        segundosDescanso: 60,
        pesoKg: 25,
        seriesConcluidas: 0,
      },
      {
        id: 'ex-10',
        name: 'Abdominal Crunch',
        grupoMuscular: 'Core',
        sets: 3,
        reps: '20',
        segundosDescanso: 45,
        seriesConcluidas: 0,
      },
    ],
  },
  {
    id: 'plan-3',
    name: 'Força — Avançado',
    alunoId: 'student-4',
    professorId: 'user-3',
    dificuldade: 'avancado',
    diasPorSemana: 4,
    criadoEm: '2024-04-05T10:00:00Z',
    atualizadoEm: '2024-05-15T10:00:00Z',
    ativo: true,
    exercicios: [
      {
        id: 'ex-11',
        name: 'Levantamento Terra',
        grupoMuscular: 'Costas / Glúteos',
        sets: 5,
        reps: '5',
        segundosDescanso: 180,
        pesoKg: 100,
        notes: 'Cinturão obrigatório acima de 80kg',
        seriesConcluidas: 0,
      },
      {
        id: 'ex-12',
        name: 'Agachamento Frontal',
        grupoMuscular: 'Pernas',
        sets: 4,
        reps: '6',
        segundosDescanso: 150,
        pesoKg: 70,
        seriesConcluidas: 0,
      },
    ],
  },
];


export const MOCK_EQUIPMENT: Equipamento[] = [
  {
    id: 'eq-1',
    name: 'Esteira Ergométrica #1',
    category: 'Cardio',
    brand: 'Movement',
    model: 'LX 160i',
    status: 'funcionando',
    location: 'Área Cardio',
    ultimaManutencaoEm: '2024-02-15T10:00:00Z',
    proximaManutencaoEm: '2024-08-15T10:00:00Z',
    compradoEm: '2022-01-10T10:00:00Z',
  },
  {
    id: 'eq-2',
    name: 'Esteira Ergométrica #2',
    category: 'Cardio',
    brand: 'Movement',
    model: 'LX 160i',
    status: 'manutencao',
    location: 'Área Cardio',
    ultimaManutencaoEm: '2024-05-01T10:00:00Z',
    notes: 'Correia de transmissão fora do eixo',
  },
  {
    id: 'eq-3',
    name: 'Bike Ergométrica',
    category: 'Cardio',
    brand: 'Kikos',
    model: 'F.Bike',
    status: 'funcionando',
    location: 'Área Cardio',
    ultimaManutencaoEm: '2024-03-20T10:00:00Z',
  },
  {
    id: 'eq-4',
    name: 'Leg Press 45° #1',
    category: 'Força',
    brand: 'Hammer',
    status: 'funcionando',
    location: 'Sala de Musculação',
    ultimaManutencaoEm: '2024-04-01T10:00:00Z',
  },
  {
    id: 'eq-5',
    name: 'Leg Press 45° #2',
    category: 'Força',
    brand: 'Hammer',
    status: 'quebrado',
    location: 'Sala de Musculação',
    notes: 'Guia da cremalheira quebrada — aguardando peça',
  },
  {
    id: 'eq-6',
    name: 'Polia Alta / Crossover',
    category: 'Força',
    brand: 'Olympikus',
    status: 'funcionando',
    location: 'Sala de Musculação',
    ultimaManutencaoEm: '2024-01-15T10:00:00Z',
  },
  {
    id: 'eq-7',
    name: 'Supino Guiado',
    category: 'Força',
    brand: 'WCT Fitness',
    status: 'funcionando',
    location: 'Sala de Musculação',
  },
  {
    id: 'eq-8',
    name: 'Cadeira Extensora',
    category: 'Força',
    brand: 'Hammer',
    status: 'manutencao',
    location: 'Sala de Musculação',
    notes: 'Parafusos de regulagem frouxos',
  },
  {
    id: 'eq-9',
    name: 'Rack de Halteres (5-40kg)',
    category: 'Livre',
    brand: 'Kikos',
    status: 'funcionando',
    location: 'Área de Pesos Livres',
  },
  {
    id: 'eq-10',
    name: 'Barra Olímpica #1',
    category: 'Livre',
    status: 'funcionando',
    location: 'Área de Pesos Livres',
  },
  {
    id: 'eq-11',
    name: 'Elíptico',
    category: 'Cardio',
    brand: 'Caloi',
    model: 'CL-E10',
    status: 'funcionando',
    location: 'Área Cardio',
    ultimaManutencaoEm: '2024-02-01T10:00:00Z',
  },
  {
    id: 'eq-12',
    name: 'Smith Machine',
    category: 'Força',
    brand: 'Hammer',
    status: 'funcionando',
    location: 'Sala de Musculação',
    ultimaManutencaoEm: '2024-03-10T10:00:00Z',
  },
];


export const MOCK_ALERTS: AlertaAcademia[] = [
  {
    id: 'alert-1',
    title: '🔧 Leg Press #2 Temporariamente Fora de Uso',
    message:
      'O Leg Press 45° #2 está temporariamente fora de uso. A peça substituta foi solicitada e chegará em até 5 dias úteis. Pedimos desculpas pelo transtorno.',
    type: 'warning',
    perfilAlvo: 'todos',
    autorId: 'user-3',
    nomeAutor: 'Rafael Costa',
    criadoEm: '2024-05-25T09:00:00Z',
    lido: false,
  },
  {
    id: 'alert-2',
    title: '🎉 Promoção: Traga um Amigo — Desconto de 20%',
    message:
      'Durante o mês de junho, indique um amigo e ganhe 20% de desconto na sua próxima mensalidade! Fale com a recepção para mais detalhes.',
    type: 'success',
    perfilAlvo: 'aluno',
    autorId: 'user-5',
    nomeAutor: 'Marcos',
    criadoEm: '2024-05-24T14:00:00Z',
    lido: false,
  },
  {
    id: 'alert-3',
    title: '⚠️ Academia Fechada — Feriado 12/06',
    message:
      'Informamos que a academia estará fechada no dia 12 de junho (Corpus Christi). Retornaremos normalmente no dia 13/06.',
    type: 'info',
    perfilAlvo: 'todos',
    autorId: 'user-5',
    nomeAutor: 'Marcos',
    criadoEm: '2024-05-23T16:00:00Z',
    lido: true,
  },
  {
    id: 'alert-4',
    title: '💧 Manutenção do Bebedouro',
    message:
      'O bebedouro da sala de musculação passará por manutenção amanhã das 8h às 10h. Recomendamos trazer garrafinhas.',
    type: 'info',
    perfilAlvo: 'todos',
    autorId: 'user-3',
    nomeAutor: 'Enrico',
    criadoEm: '2024-05-22T11:00:00Z',
    lido: true,
  },
];


export const MOCK_MAINTENANCE_REQUESTS: SolicitacaoManutencao[] = [
  {
    id: 'maint-1',
    equipamentoId: 'eq-5',
    nomeEquipamento: 'Leg Press 45° #2',
    solicitadoPorId: 'user-3',
    nomeSolicitante: 'Enrico',
    description:
      'A guia da cremalheira está quebrada. O aparelho está totalmente inutilizável e representa risco de segurança.',
    priority: 'alta',
    status: 'aprovada',
    custoEstimadoBRL: 450.0,
    aprovadoPorId: 'user-5',
    criadoEm: '2024-05-24T10:00:00Z',
    notes: 'Aguardando chegada da peça. Previsão: 5 dias úteis.',
  },
  {
    id: 'maint-2',
    equipamentoId: 'eq-2',
    nomeEquipamento: 'Esteira Ergométrica #2',
    solicitadoPorId: 'user-4',
    nomeSolicitante: 'Beatriz',
    description: 'Correia de transmissão saiu do eixo. Esteira emitindo ruído e velocidade instável.',
    priority: 'media',
    status: 'pendente',
    custoEstimadoBRL: 280.0,
    criadoEm: '2024-05-26T08:00:00Z',
  },
  {
    id: 'maint-3',
    equipamentoId: 'eq-8',
    nomeEquipamento: 'Cadeira Extensora',
    solicitadoPorId: 'user-3',
    nomeSolicitante: 'Enrico',
    description: 'Parafusos de regulagem de peso estão frouxos. Aparelho trepida durante o uso.',
    priority: 'baixa',
    status: 'pendente',
    custoEstimadoBRL: 80.0,
    criadoEm: '2024-05-27T07:30:00Z',
  },
  {
    id: 'maint-4',
    equipamentoId: 'eq-3',
    nomeEquipamento: 'Bike Ergométrica',
    solicitadoPorId: 'user-4',
    nomeSolicitante: 'Beatriz',
    description: 'Display do painel não exibe corretamente as calorias queimadas.',
    priority: 'baixa',
    status: 'concluida',
    custoEstimadoBRL: 120.0,
    aprovadoPorId: 'user-5',
    criadoEm: '2024-05-10T09:00:00Z',
    resolvidoEm: '2024-05-15T14:00:00Z',
    notes: 'Display substituído. Aparelho em perfeito funcionamento.',
  },
];


export const MOCK_FINANCIAL_SUMMARY: ResumoFinanceiro = {
  totalAlunos: 6,
  adimplentes: 3,
  inadimplentes: 2,
  pendentes: 1,
  receitaMensalBRL: 570.0,
  receitaEsperadaBRL: 810.0,
  taxaInadimplenciaPercentual: 33.3,
};

export const MOCK_REVENUE_DATA: PontoReceita[] = [
  { month: 'Jan', receita: 720, esperado: 800, inadimplencia: 80 },
  { month: 'Fev', receita: 750, esperado: 800, inadimplencia: 50 },
  { month: 'Mar', receita: 810, esperado: 850, inadimplencia: 40 },
  { month: 'Abr', receita: 680, esperado: 850, inadimplencia: 170 },
  { month: 'Mai', receita: 570, esperado: 810, inadimplencia: 240 },
];


export const MOCK_KPI: KpiGerencia = {
  totalAlunos: 6,
  alunosAtivos: 5,
  novosAlunosEsteMes: 1,
  cancelamentosEsteMes: 0,
  totalEquipamentos: 12,
  problemasEquipamento: 3,
  manutencoesPendentes: 2,
  receitaMensalBRL: 570.0,
  taxaInadimplenciaPercentual: 33.3,
  frequenciaMediaPorDia: 18,
};
